version: '3.7'

services:
  sshclient:
    image: wolke77/sshclient-gateway:latest
    build: ./build
    restart: unless-stopped
    volumes:
      - ./sshclient:/sshclient
    environment:
      - SSH_REMOTE_USER=ansible
      - SSH_REMOTE_HOST=jumpserver.example.com
      - SSH_REMOTE_PORT=22
      - TUN_REMOTE_BIND_ADDRESS=127.22.0.1 # requires sshd_config GatewayPort clientspecified. Otherwise will default to localhost
      - TUN_REMOTE_BIND_PORT=22022
      - TUN_TARGET_HOST=server1.lan
      - TUN_TARGET_PORT=22
